name: Byg docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v4

      - name: login to GitHub container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/dockerkode:latest ./DockerKubernetes

      - name: Run docker image
        run: docker run ghcr.io/${{ github.repository_owner }}/dockerkode:latest

      - name: Push docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/dockerkode:latest